export const GET_GENRE_CODES = 'GET_GENRE_CODES';
export const GENRE_DROPDOWN_DATA_SOURCE = 'GENRE_DROPDOWN_DATA_SOURCE';
export const IS_FETCHING_GENRES = 'IS_FETCHING_GENRES';
export const SUBMIT_SPIN = 'SUBMIT_SPIN';
export const SAVE_SELECTION = 'SAVE_SELECTION';
export const START_SPINNING = 'START_SPINNING';
export const STOP_SPINNING = 'STOP_SPINNING';
